# gcc
[tasks.gcc-build]
description = "Build C code with gcc according to my rules."
command = "sh"
args=["_makers_script/build-gcc.sh", "${@}"]

[tasks.run-c]
description = "Run sample-codes exe file made by c code"
cwd="sample-codes/exe/"
script = ["%*.exe"]

# オブジェクトファイル作成
[tasks.gc-print]
description = "alias for gcc-compile-print. Compile shared/print.c to object file."
command = "gcc"
args=["-c","sample-codes/shared/print.c", "-o", "sample-codes/shared/obj/print.o"]

# 実行ファイル作成
[tasks.gb-bubble]
description = "alias for gcc-build-bubble. Build bubble.c"
command = "gcc"
args=["sample-codes/bubble.c", "sample-codes/shared/obj/print.o", "-o", "sample-codes/exe/bubble.exe"]
dependencies = ["gc-print"]

[tasks.gb-linked-list]
description = "alias for gcc-build-linked-list. Build linked-list.c"
command = "gcc"
args=["sample-codes/linked-list.c", "-o", "sample-codes/exe/linked-list.exe"]

[tasks.gb-cdl-list]
description = "alias for gcc-build-circular-doubly-linked-list. Build cdl-list.c"
command = "gcc"
args=["sample-codes/cdl-list.c", "-o", "sample-codes/exe/cdl-list.exe"]
