[package]
name = "code"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
deno_ast = "0.48.0"
serde = "1.0.219"
serde_json = "1.0.140"
swc_visit = "2.0.1"
